### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by xyproto** [google/gxui#59] opened 2015-03-23 08:52 UTC
When running the progress_bar sample, everything works, but when closing the windows, this happens:

~~~
panic: send on closed channel

goroutine 422 [running]:
github.com/google/gxui/themes/dark.func·011()
	/home/alexander/go/src/github.com/google/gxui/themes/dark/progress_bar.go:31 +0xf1
created by time.goFunc
	/usr/lib/go/src/time/sleep.go:129 +0x4b

goroutine 1 [syscall, locked to thread]:
github.com/go-gl/glfw/v3.1/glfw._Cfunc_glfwTerminate()
	/home/alexander/go/src/github.com/go-gl/glfw/v3.1/glfw/:868 +0x45
github.com/go-gl/glfw/v3.1/glfw.Terminate()
	/home/alexander/go/src/github.com/go-gl/glfw/v3.1/glfw/glfw.go:48 +0x20
github.com/google/gxui/drivers/gl.StartDriver(0x8fbef8)
	/home/alexander/go/src/github.com/google/gxui/drivers/gl/driver.go:48 +0x1e6
main.main()
	/home/alexander/go/src/github.com/google/gxui/samples/progress_bar/main.go:50 +0x2a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
~~~

Using latest commit on master (4c80f4e85c397bd6fe7354373151b0a922f0a465)
go version go1.4.2 linux/amd64
64-bit Arch Linux

Best regards,
  Alexander F Rødseth

**Comment by ben-clayton** [comment] 2015-03-23 10:52
Possibly related to #48

**Comment by xyproto** [comment] 2015-03-23 11:09
I looked at #48 first, but the error messages are pretty different.

**Comment by tones111** [comment] 2015-03-24 02:52
I think this is a different from #48.  Running with the race detector the relevant info is...

WARNING: DATA RACE
Read by goroutine 47:
  runtime.chansend()
      /build/go/src/go-1.4.2/src/runtime/chan.go:83 +0x0
  github.com/google/gxui/themes/dark.func·011()
      /home/paul/src/gosrc/src/github.com/google/gxui/themes/dark/progress_bar.go:39 +0x312

Previous write by main goroutine:
  runtime.closechan()
      /build/go/src/go-1.4.2/src/runtime/chan.go:257 +0x0
  github.com/google/gxui/drivers/gl.func·013()
      /home/paul/src/gosrc/src/github.com/google/gxui/drivers/gl/driver.go:115 +0x1e3
  github.com/google/gxui/drivers/gl.(*Driver).run()
      /home/paul/src/gosrc/src/github.com/google/gxui/drivers/gl/driver.go:85 +0x90
  github.com/google/gxui/drivers/gl.StartDriver()
      /home/paul/src/gosrc/src/github.com/google/gxui/drivers/gl/driver.go:47 +0x23d
  main.main()
      /home/paul/src/gosrc/src/github.com/google/gxui/samples/progress_bar/main.go:50 +0x37

Goroutine 47 (running) created at:
  time.goFunc()
      /build/go/src/go-1.4.2/src/time/sleep.go:129 +0x59


The problem is that there is no communication mechanism to notify the contols of impending termination.  The driver attempts to flush any outstanding events prior to closing the event channels, but it's useless because it never told the controls to stop sending events.

There probably needs to be some sort of onTerminate or onDestroy event implemented by any object in the system.  As parent objects (containers) are destroyed they would first propagate the signal to their children before then doing any necessary cleanup themselves.  After everything has had a chance to clean up then the flush and channel closing can be done.

**Comment by ben-clayton** [comment] 2015-03-28 19:13
This should now be fixed. Please reopen if not.

**Closed by ben-clayton** 2015-03-28 19:13 UTC

**Comment by xyproto** [comment] 2015-03-28 20:45
Thanks!
