### ISSUE TITLE
input

### ISSUE THREAD

**Issue by bonly** [google/gxui#99] opened 2015-04-09 10:10 UTC
how can I input chinese? with XIM? and how about the chinese like (w_char) fonts?

**Comment by ben-clayton** [comment] 2015-04-09 23:44
Duplicate of #60.

**Closed by ben-clayton** 2015-04-09 23:44 UTC

**Comment by mattn** [comment] 2015-04-10 03:18
@bonly FYI: you can do it with https://github.com/mattn/glfw/commit/d48fc47dc96d7486539c3cf22617f747f36f5c62

**Comment by bonly** [comment] 2015-04-24 05:48
thanks to mattn! It works
